# Generated by Django 6.1.1 on 2026-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs_app', '0028_auto_20220703_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='substitutes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
